FROM alpine:latest

# atualiza e instala o nginx. A flag --no-cache ta sendo utilizada pra diminuir a memoria
RUN apk update && apk add --no-cache nginx

# copia o arquivo de configuração desse diretório para o container
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80

# referencia: https://stackoverflow.com/questions/18861300/how-to-run-nginx-within-a-docker-container-without-halting 
CMD ["nginx", "-g", "daemon off;"]
